### ISSUE TITLE
Add gulp-sourcemaps support

### ISSUE THREAD

**Issue by shelldandy** [avaly/gulp-group-css-media-queries#13]
https://github.com/gulp-sourcemaps/gulp-sourcemaps#plugin-developers-only

I can submit a PR

**Comment by avaly** [comment]
@mike3run Please do send a PR. I'm not actively using this package, so I'll rely on PRs from now on.

**Comment by shelldandy** [comment]
@avaly thanks for replying so fast gives me hope the pr will be be reviewed and merged faster
