### ISSUE TITLE
Remove gulp-util as dependency 

### ISSUE THREAD

**Issue by shelldandy** [avaly/gulp-group-css-media-queries#14]
See: Help us fix the ecosystem

Almost at end of post

https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by shelldandy** [comment]
https://www.npmjs.com/package/plugin-error

**Comment by shelldandy** [comment]
I'll do this as well @avaly no problem

**Comment by avaly** [comment]
Closed by https://github.com/avaly/gulp-group-css-media-queries/pull/15
